### ISSUE TITLE
"Symbola" Font is Required for Icons to Not Be Broken On Windows 10

### ISSUE THREAD

**Issue by davidpgil** [seagle0128/.emacs.d#123]
Issue #121 required that I install a non-free font in order to fix broken icons in Windows 10 and Emacs 26.3.

I am opening this issue so that an alternative libre (free software) font is used to solve this issue.

**Comment by seagle0128** [comment]
I don't think the `Symbola` font is necessary since I didn't install it but all icons are displayed correctly. Maybe other fonts provide the required glyph. 

Moreover, this issue is related to the upstream `all-the-icons`. Have nothing to do with `doom-modeline`. The FAQ has been updated in 723b96357465426edd672c3af428e3e80dda663d. I think that's good enough.

**Comment by davidpgil** [comment]
You have Centaur Emacs installed with Windows 10 and you did not have broken icons?

With free software licenses, *I believe* you are not supposed to recommend installing something that is against the license. Do you care if Centaur Emacs has consistent licensing?

**Comment by seagle0128** [comment]
@davidpgil For me, it works fine with Window 10. I don't know why it's broken in your env.
