### ISSUE TITLE
Add TIDE and Typescript mode

### ISSUE THREAD

**Issue by cmgustavo** [seagle0128/.emacs.d#79]
In description says that it includes support for Typescript, but sincerely it seems to do not have any support. It hasn't syntax highlight.

Please, add TIDE (https://github.com/ananthakumaran/tide) and typescript-mode (https://github.com/emacs-typescript/typescript.el)!

Thanks!

**Comment by seagle0128** [comment]
`tide` was removed while cleaning non-lsp packages. I will add `typescript-mode` back for syntax highlight. Please use `lsp-mode` or `eglot` with [typescript-language-server](https://github.com/theia-ide/typescript-language-server) or [javascript-typescript-langserver](https://github.com/sourcegraph/javascript-typescript-langserver) for development. `typescript-language-server` is recommended since it has better experience. It's just a wrapper of tide server.
